# Generated by Django 6.1.1 on 2026-09-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('HOSPITAL', 'Hospital'), ('BLOOD_BANK', 'Blood Bank'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
    ]
