# Generated by Django 6.1.1 on 2026-09-23 16:40

from django.db import migrations


def migrate_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role__in=['DONOR', 'REQUESTER']).update(role='USER')

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_unify_roles'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_code=migrations.RunPython.noop),
    ]
