# Generated by Django 6.1.1 on 2026-09-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NOTIFIED', 'Notified'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='blood_requests.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='donors.donorprofile')),
            ],
            options={
                'verbose_name': 'donor matching',
                'verbose_name_plural': 'donor matchings',
                'indexes': [models.Index(fields=['blood_request'], name='matching_do_blood_r_ca73b5_idx'), models.Index(fields=['donor'], name='matching_do_donor_i_ba966a_idx'), models.Index(fields=['status'], name='matching_do_status_fbd585_idx')],
                'constraints': [models.UniqueConstraint(fields=('blood_request', 'donor'), name='unique_blood_request_donor_match')],
            },
        ),
    ]
